title: "Jade (Lei) Yu"
author: "Jade Yu"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"

show_footer: true           # show the "previous" and "next" links at the end of each post
dark_theme: true            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme
mathjax: true

navigation:                  # site navigation in the header
  - index.html
  - education.html
  - publications.html
  - cv.html

icons:                      # icons in the header, see http://fontawesome.com/icons
 envelope: "mailto:jadeleiyu@cs.toronto.edu"
 github: "https://github.com/jadeleiyu"
 rss: "feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout

theme: jekyll-theme-slate
