title: "Jingyi(Kylie) He | 何靖怡"
author: "Jingyi(Kylie) He"
description: "Really cool blog about ... something"
permalink: /:title/
lang: "en"

show_footer: true           # show the "previous" and "next" links at the end of each post
dark_theme: true            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme
mathjax: true

navigation:                  # site navigation in the header
  - main.md
  - technical_posts.html
  - personal_posts.html

icons:                      # icons in the header, see http://fontawesome.com/icons
 envelope: 
 github: "https://github.com/kylie-box"
 rss: "feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout
